### ISSUE TITLE
Readme: ObjImporter Link not Working

### ISSUE THREAD

**Issue by ghost** [Droog71/FCE_Atmosphere_Mod#1]
I tried compiling the latest version, but it can't find ObjImporter. So, I tried the link in the readme, but the link is not good anymore.

Is this what you used? https://assetstore.unity.com/packages/tools/modeling/runtime-obj-importer-49547#description

Error during compiling:

c:\Users\Tits\Desktop\Atmosphere.cs(679,21): error CS0246: The type or namespace name 'ObjImporter' could not be found
        (are you missing a using directive or an assembly reference?)
c:\Users\Tits\Desktop\Atmosphere.cs(679,48): error CS0246: The type or namespace name 'ObjImporter' could not be found
        (are you missing a using directive or an assembly reference?)

I am using the commandline compiler csc.exe for .NET 3.5

Command used: 
"csc.exe - .NET 3.5.lnk" /t:library /R:C:\Users\Tits\Documents\64\FC_64_Data\Managed\Assembly-CSharp.dll,C:\Users\Tits\Documents\64\FC_64_Data\Managed\UnityEngine.dll C:\Users\Tits\Desktop\Atmosphere.cs

**Comment by ghost** [comment]
I found out that the Unity Wiki was taken down, so I don't know where I'd find this ObjImporter library/plugin. I just commented the code for replacing the GlowTubes. Everything works now. :)

Still, you should update the readme.

**Comment by Droog71** [comment]
The obj importer code is included in the repo now.
