### ISSUE TITLE
Are You Tired of Me Yet? :) (Loading Settings from settings.txt

### ISSUE THREAD

**Issue by ghost** [Droog71/FCE_Atmosphere_Mod#3]
Another less serious problem is loading settings from settings.txt.

When I start a new world, settings don't seem to be loading from "settings.txt".
The world starts with the defaults. The fog distance is loaded, but not the particle effects.

fog_enabled:0]fog_color:1]fog_distance:250]sky_texture:1]terrain_texture:Snow]surface_dust:0]surface_mist:0]dust_particles:0]mist_cloud:0]snow_mist:0]snow_dust:1]cold_mist:1]toxic_mist:0

(Snow Mist and Mist Cloud were also 1 in the file, but in-game, they were set to False in-game and not applied. The reason they are 0 in the text is because I manually toggled them in-game, temporarily fixing this issue.

![image](https://user-images.githubusercontent.com/38441604/167024286-dd58d961-f3ea-40f5-aae6-10832ddc4636.png)

I think this issue with loading from a file AND applying the settings automatically also happens when loading an existing world.

**Comment by ghost** [comment]
Despite using an older version of the mod (from Nexus Mods), I'll still check if these settings work.

It does appear the Cold Mist and Toxic settings in the newest version don't do anything. I guess you removed the features but forgot to remove the settings?

**Comment by Droog71** [comment]
I think the settings might have been overwritten by mod updates.
Not sure if the cold mist and toxic mist settings ever worked.
```
if (obj.name == "Toxic_Mist")
{
    toxicMist = obj;
    obj.GetComponent<Renderer>().enabled = toxic_mist == 1;
}
```
The code is there but i'm not sure if it is effective.
I don't plan to work on this.
